### ISSUE TITLE
请问一下仓库的 license 

### ISSUE THREAD

**Issue by endink** [Huiyicc/gpt_sovits_cpp#2]
使用限制？

**Comment by Huiyicc** [comment]
> 使用限制？

MIT,和gsv官方仓库一致，韩语推理写完会更新

**Comment by endink** [comment]
谢谢，晚上回去编译一下，请问有测试过 CPU stf 情况吗，如果能用 CPU 实时推理就好了，很棒的库，没看到你的库之前我差点去搞 rust 那个仓库和 C 交互了，再次感谢~

**Comment by Huiyicc** [comment]
> 谢谢，晚上回去编译一下，请问有测试过 CPU stf 情况吗，如果能用 CPU 实时推理就好了，很棒的库，没看到你的库之前我差点去搞 rust 那个仓库和 C 交互了，再次感谢~

可以使用cpu,但是推理延迟还是挺高的

**Comment by endink** [comment]
打错字了， RTF CPU 到不了 1 以下？

**Comment by Huiyicc** [comment]
具体没有详细测过,但无论是原版还是编译之后的模型,仅使用cpu都是很慢的

**Comment by endink** [comment]
OK, 我自己测试了，关闭 issue 了
