### ISSUE TITLE
编译不过去

### ISSUE THREAD

**Issue by endink** [Huiyicc/gpt_sovits_cpp#3]
我是 Windows 平台编译。

是不是代码提交漏了，首先就是测试代码使用的函数和函数定义都不匹配，比如：

- 并没有 `RegisterJapanese` 函数。
- `RegisterChinese` 参数也不匹配。

这些都可以手工改一下，注释一些没有的函数，改成:

```cpp

GPTSovits::Bert::RegisterChinese(device,
                                 currentPath + R"(/../model_base/bert_model.pt)",
                                 currentPath + R"(/../model_base/tokenizer.json)");
GPTSovits::Bert::RegisterEnglish(device);
//GPTSovits::Bert::RegisterJapanese(*gpt_sovits, true);

gpt_sovits->CreateSpeaker("firefly",
                          currentPath + "/../model/gpt_sovits_model.pt",
                          currentPath + "/../model/ref.wav",
                          "虽然我也没太搞清楚状况,但他说，似乎只有直率、纯真、有童心的小孩子才能看见它.", "zh");

```

主要是编译时候 `tokenizers_c` 依赖会出问题：

```
Generating x86_64-pc-windows-msvc/release/tokenizers_c.lib
Building Custom Rule F:/Works/gpt_sovits_cpp/CppModels/tokenizers-cpp/sentencepiece/src/CMakeLists.txt
no such file or directory

// 这里卡住了，导致最终编译失败
```

我的步骤是这样：

- `clone  cpp modules`: git clone --recursive https://github.com/Huiyicc/CppModels

- cmake -DCMAKE_BUILD_TYPE=Rease .. -G "Visual Studio 17 2022" -DTorch_DIR="XXX"

我觉得配置没有什么问题，就 CUDA 和 CUDNN 配置一下，主要是   CppModels 这项目和 test 代码是不是年久失修？

**Comment by Huiyicc** [comment]
分支切换成dev试试

**Comment by Huiyicc** [comment]
tokenizers编译失败的话cd 进去看看是不是依赖的子模块没有clone

**Comment by endink** [comment]
git clone --recursive 应该不会丢啊，我看过 clone 记录是没有错误的

**Comment by Huiyicc** [comment]
> git clone --recursive 应该不会丢啊，我看过 clone 记录是没有错误的

tokenizers-cpp里面还有依赖msgpack 和sentencepiece

**Comment by endink** [comment]
依赖都有的，我随便看了一眼这个 CMAKE，是不是你这个 libtokenizers_c.lib 是个 RUST 库啊，但是源码里又不提供

**Comment by Huiyicc** [comment]
> 依赖都有的，我随便看了一眼这个 CMAKE，是不是你这个 libtokenizers_c.lib 是个 RUST 库啊，但是源码里又不提供

tokenizers本身是rust库,做了中间层加到了c++上，所以需要有rust编译器才行
![Snipaste_2024-12-24_17-43-09](https://github.com/user-attachments/assets/1dcaffbb-ac5f-4ffa-99f1-d28d366f64c6)

**Comment by endink** [comment]
啊， 没注意看， 我的问题，那我再试试，另外，这个 RegisterJapanese 函数没有，是不是还在开发啊

**Comment by Huiyicc** [comment]
> 啊， 没注意看， 我的问题，那我再试试，另外，这个 RegisterJapanese 函数没有，是不是还在开发啊

看了下，ja那部分是已经合并到了master上了的，是不是什么其他的错误？报错是什么？

![image](https://github.com/user-attachments/assets/6c935f2c-57fe-4ae2-acdb-bb31a9189067)
![image](https://github.com/user-attachments/assets/173ac2cc-a835-4bbe-b2df-df061994f2d7)

**Comment by endink** [comment]
这个函数不存在， 我觉得是因为你 CPPMODULE 里的 gpt-sovits 和这个项目的代码不一样，我编译 test 用的你现在这个项目，但是 cmake 出来的依赖好像用的 CPPMODULE 里的

**Comment by Huiyicc** [comment]
晚些我换个新环境编译下看看啥情况

**Comment by Huiyicc** [comment]
> 这个函数不存在， 我觉得是因为你 CPPMODULE 里的 gpt-sovits 和这个项目的代码不一样，我编译 test 用的你现在这个项目，但是 cmake 出来的依赖好像用的 CPPMODULE 里的

我测试了下没问题
![image](https://github.com/user-attachments/assets/b97523d1-c3d3-4180-8396-695a38e8ad37)

编译例子的话需要使用test目录里的CmakeList

**Comment by Huiyicc** [comment]
> > 这个函数不存在， 我觉得是因为你 CPPMODULE 里的 gpt-sovits 和这个项目的代码不一样，我编译 test 用的你现在这个项目，但是 cmake 出来的依赖好像用的 CPPMODULE 里的
> 
> 我测试了下没问题 ![image](https://private-user-images.githubusercontent.com/10141057/398400375-b97523d1-c3d3-4180-8396-695a38e8ad37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzk0NTYsIm5iZiI6MTczNTAzOTE1NiwicGF0aCI6Ii8xMDE0MTA1Ny8zOTg0MDAzNzUtYjk3NTIzZDEtYzNkMy00MTgwLTgzOTYtNjk1YTM4ZThhZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDExMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYjY0NDAxZWFiMjA5MjI1ODUxZDQwN2YyNzMzYjdhYjZkMmUxNjI4ZjIwOGNhMTM3ZDMwNDY1MGM1MmVmODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3TptGEYoWbSVdqP9b1P7gUKsLKfKwauAIP7-o_yYDSk)
> 
> 编译例子的话需要使用test目录里的CmakeList

cd CppModels/gpt_sovits_cpp/test/
mkdir build
cd build/
cmake .. -DTorch_DIR=/usr/local/libtorch -DCMAKE_BUILD_TYPE=Release

**Comment by endink** [comment]
我是编译例子，我编译过去了，但是改了代码，我不知道哪种写法是最新的，但是我相信 RegisterJapanese 丢失应该是旧的

**Comment by endink** [comment]
我直接给你个 bat 吧：

```bat

set "PROJECT_DIR=F:\Works\gpt_sovits_cpp"
set "TORCH_DIR=F:\Works\libtorch_2.5.1_cu124"

CHCP 65001

set "third_party_dir=%PROJECT_DIR%\third_party"
set "TARGET_PROJ_DIR=%PROJECT_DIR%\test"
set "CPPMODULES_DIR=%PROJECT_DIR%\CppModels"
set "nvtx3_dir=%third_party_dir%\NVTX"

if not EXIST "%third_party_dir%" (
    mkdir "%third_party_dir%"
)

if not EXIST "%CPPMODULES_DIR%" (
    @echo Clone CPPMODULES ...
    pushd "%PROJECT_DIR%"
    git clone --recursive https://github.com/Huiyicc/CppModels
)


if not EXIST "%nvtx3_dir%" (
    @echo Clone NVTX ...
    pushd "%third_party_dir%"
    git clone --recursive https://github.com/NVIDIA/NVTX.git
)


set BUILD_CONFIG=Release
set "BUILD_DIR=%TARGET_PROJ_DIR%\build"

pushd "%TARGET_PROJ_DIR%"

if not EXIST "%BUILD_DIR%" (
    mkdir "%BUILD_DIR%"
)

cd build
set "CPPMODULES=%CPPMODULES_DIR%"

cmake -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% .. -G "Visual Studio 17 2022" ^
    -DTorch_DIR="%TORCH_DIR%"
    
@rem -DCMAKE_CXX_FLAGS="/utf8 /source-charset:utf-8" ^
@rem -DCMAKE_C_FLAGS="/utf8 /source-charset:utf-8" ^
@rem -DBUILD_SHARED_LIBS=1

@rem make

pause
```

**Comment by endink** [comment]
这个问题其实就是 CppModels 里那个子模块 `gpt_sovits_cpp` 不是最新的, 当 clone `gpt_sovits_cpp` 仓库时，里面的 test 又要依赖 `CppModels `， 这样就会让 test 依赖 CppModels  的 `gpt_sovits_cpp`, 而不是 gpt_sovits_cpp 仓库的 `gpt_sovits_cpp`，你那个 CppModels  里的那份又和这个仓库不同步，所以... 我觉得不要合并到 CppModels  合理一点吧，我看你那个 CppModels  是些基础库，这个明明是个功能

**Comment by endink** [comment]
还有这个仓库如果没有旧版 NVTX 也没有办法编译，多旧我不知道，我的环境有 cuda11.6 和 cuda 12 我都没法编译，因为他们都在找旧版的 nvtx, 解决办法就是clone 这个 https://github.com/NVIDIA/NVTX 放在 third_party 目录下，因为 Coffee2 那个 cuda.cmake 会来找这个，nvtx3 只有头文件了，而旧的有个 lib 文件，所以不手工处理也编译不过去

**Comment by endink** [comment]
我那个 bat 要编译你的例子我只能改成这样:

```
auto gpt_config = GPTSovits::GPTSovitsConfig::Make("zh",
                                                   currentPath + R"(/../model_base/ssl_model.pt)");
auto gpt_sovits = gpt_config->Build(device);

GPTSovits::Bert::RegisterChinese(device,
                                 currentPath + R"(/../model_base/bert_model.pt)",
                                 currentPath + R"(/../model_base/tokenizer.json)");
GPTSovits::Bert::RegisterEnglish(device);
//GPTSovits::Bert::RegisterJapanese(*gpt_sovits, true);
```

虽然编译成功了，还是废了点劲啊

**Comment by Huiyicc** [comment]
感谢测试，刚看了下CppModel这个且是没同步，后面我把依赖库迁移到项目的third_party吧，至于nvtx3这个问题，libtorch仓库有这议题，官方也一直没解决，只能自己手动处理下😂
这个坑我博客是写了解决方法的，不过也仅限windows，linux不会有这些幺蛾子🤣
![image](https://github.com/user-attachments/assets/83e3df85-5eb0-4e00-9375-67421db0f1a8)

**Comment by endink** [comment]
nvtx 这个你其实就是 third_party 目录下克隆一下 NVTX 仓库，他自己就会找到 v3 版本了，这个跑回去安装 cuda 11 很烦人啊

**Comment by endink** [comment]
不客气哈 ~~ 我自己想要用你劳动成果，动点手应该得，总体编译还是很顺利的

**Comment by Huiyicc** [comment]
> nvtx 这个你其实就是 third_party 目录下克隆一下 NVTX 仓库，他自己就会找到 v3 版本了，这个跑回去安装 cuda 11 很烦人啊

已收到，后续更新会先将依赖和编译部署问题解决√

**Comment by endink** [comment]
```cmake
# nvToolsExt
find_path(nvtx3_dir NAMES nvtx3 PATHS "${PROJECT_SOURCE_DIR}/third_party/NVTX/c/include" NO_DEFAULT_PATH)
find_package_handle_standard_args(nvtx3 DEFAULT_MSG nvtx3_dir)
if(nvtx3_FOUND)
  add_library(torch::nvtx3 INTERFACE IMPORTED)
  target_include_directories(torch::nvtx3 INTERFACE "${nvtx3_dir}")
  target_compile_definitions(torch::nvtx3 INTERFACE TORCH_CUDA_USE_NVTX3)
else()
  message(WARNING "Cannot find NVTX3, find old NVTX instead")
  message(WARNING "Path: ${PROJECT_SOURCE_DIR}/third_party/NVTX/c/include")
  add_library(torch::nvtoolsext INTERFACE IMPORTED)
  set_property(TARGET torch::nvtoolsext PROPERTY INTERFACE_LINK_LIBRARIES CUDA::nvToolsExt)
endif()
```

那个用 V3 还是 V2 的逻辑，就是如果你项目下有 third_party/NVTX 他就判定是 V3，就不需要 .lib 了，所以只要你这个仓库里带个 third_party/NVTX 就 OK 了

**Comment by endink** [comment]
好了，关闭吧，后来的同学也可以参考这些了~
