### ISSUE TITLE
RegisterChinese 用到的 token 字典文件在哪里？

### ISSUE THREAD

**Issue by endink** [Huiyicc/gpt_sovits_cpp#4]
`RegisterChinese` 函数需要字典文件啊，这个文件去哪里下载？用的 BPE 来处理中文吗？ 有没有自己提供文本前端的 API ？

**Comment by Huiyicc** [comment]
一个bert,一个tokenizer,bert在export阶段导出了,tokenizer用的[chinese-roberta-wwm-ext-large](https://huggingface.co/lj1995/GPT-SoVITS/tree/main/chinese-roberta-wwm-ext-large)里面的tokenizer.json,底层分词使用jieba 和 cpppinyin ，我fork的库里面全部都做好了

**Comment by endink** [comment]
谢谢，有的代码直接把入参引用类型给 move 了，这个是不是不太友好啊，外面的代码可能还在用这些变量啊， 例如 `BertCN` 构造函数

**Comment by Huiyicc** [comment]
> 谢谢，有的代码直接把入参引用类型给 move 了，这个是不是不太友好啊，外面的代码可能还在用这些变量啊， 例如 `BertCN` 构造函数

确实，这个应该是之前改参数的时候忘记删除实现的move了🤯

**Comment by Huiyicc** [comment]
master最新提交已修复，构建依赖相关也已迁移√
